name: VillagerBedFix
version: 1.1
main: com.example.villagerbedfix.VillagerBedFix
api-version: 1.21
description: A plugin that fixes villager pathfinding to beds.
commands:
  villagerbedfix:
    description: Teleports villagers to their nearest bed.
    usage: /<command>
